all:
  hosts:
    deploy:
  children:
    local:
      hosts:
        koffer:
          ansible_user: root
          ansible_connection: local
        konductor:
          ansible_user: root
          ansible_connection: local
        cloudctl:
          ansible_connection: ssh
          ansible_host: 10.88.0.1
          ansible_user: root
          ansible_port: 22
