---
apiVersion: networkaddonsoperator.network.kubevirt.io/v1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  imagePullPolicy: IfNotPresent
  kubeMacPool: {}
  kubeSecondaryDNS: {}
  linuxBridge: {}
  macvtap: {}
  multus: {}
  multusDynamicNetworks: {}
  ovs: {}
  ##############################################################################
  # CCIO Appended
  ##############################################################################
  selfSignConfiguration:
    caRotateInterval: 168h
    caOverlapInterval: 24h
    certRotateInterval: 24h
    certOverlapInterval: 8h
  placementConfiguration:
    workloads:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    infra:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
